### PR TITLE
[java][sdk] update diem's client-sdk-java

### PR DESCRIPTION
**Pull request by jnaulty**
In an effort to rename the Libra to Diem, upgrading the client-sdk-java
dependency from org.libra to com.diem as well as upgrading the version
from 0.0.3 to 1.0.2

### CODE REVIEW

**Comment by jnaulty** [comment]
Running into the following test failures:
```
Build Done! jar could be found at /test/java/build/libs
moved to: /test/java/build/libs
Execute java examples:
Generate keys example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GenerateKeysExampleGenerated address: F4F99EB296419EF7C41D51A1DF53B3E9
Auth Key (HEX): EB6A7B6D8F14C0F75CBCBE74648F031EF4F99EB296419EF7C41D51A1DF53B3E9
Public key (HEX): 5AC795A4FC2FF91E6E100DA7E21C7DD94EE558A1843544B9DC63951A4B99EEA5
Mint Example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.MintExampleGenerated address: 5E0F0C0D727205DCCC6085071B98AD13
Exception in thread "main" java.lang.RuntimeException: Mint coins failed
        at com.diem.Testnet.mintCoins(Testnet.java:68)
        at example.MintExample.main(MintExample.java:29)
Caused by: com.diem.jsonrpc.DiemTransactionExecutionFailedException: transaction execution failed: type: "miscellaneous_error"

        at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:224)
        at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:198)
        at com.diem.Testnet.lambda$mintCoins$0(Testnet.java:63)
        at com.diem.jsonrpc.Retry.execute(Retry.java:24)
        at com.diem.Testnet.mintCoins(Testnet.java:60)
        ... 1 more
Get Account Example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GetAccountInfoExampleException in thread "main" java.lang.RuntimeException: Mint coins failed
        at com.diem.Testnet.mintCoins(Testnet.java:68)
        at example.GetAccountInfoExample.main(GetAccountInfoExample.java:24)
Caused by: com.diem.jsonrpc.DiemTransactionExecutionFailedException: transaction execution failed: type: "miscellaneous_error"

        at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:224)
        at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:198)
        at com.diem.Testnet.lambda$mintCoins$0(Testnet.java:63)
        at com.diem.jsonrpc.Retry.execute(Retry.java:24)
        at com.diem.Testnet.mintCoins(Testnet.java:60)
        ... 1 more
Intent Identifier Example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.IntentIdentifierExampleEncoded IntentIdentifier: diem://tdm1p82gppw3w6awah2usxne2auyfsuqqqqqqqqqqqqq95y9t9?am=10000000&c=Coin1
Account (HEX) from intent: 3A9010BA2ED75DDBAB9034F2AEF08987
Amount from intent: 10000000
Currency from intent: Coin1
Submit Peer To Peer Transaction Example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.SubmitPeerToPeerTransactionExampleException in thread "main" java.lang.RuntimeException: Mint coins failed
        at com.diem.Testnet.mintCoins(Testnet.java:68)
        at example.SubmitPeerToPeerTransactionExample.main(SubmitPeerToPeerTransactionExample.java:34)
Caused by: com.diem.jsonrpc.DiemTransactionExecutionFailedException: transaction execution failed: type: "miscellaneous_error"

        at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:224)
        at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:198)
        at com.diem.Testnet.lambda$mintCoins$0(Testnet.java:63)
        at com.diem.jsonrpc.Retry.execute(Retry.java:24)
        at com.diem.Testnet.mintCoins(Testnet.java:60)
        ... 1 more
Get Events Example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GetEventsExampleException in thread "main" java.lang.RuntimeException: Mint coins failed
        at com.diem.Testnet.mintCoins(Testnet.java:68)
        at example.GetEventsExample.main(GetEventsExample.java:27)
Caused by: com.diem.jsonrpc.DiemTransactionExecutionFailedException: transaction execution failed: type: "miscellaneous_error"

        at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:224)
        at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:198)
        at com.diem.Testnet.lambda$mintCoins$0(Testnet.java:63)
        at com.diem.jsonrpc.Retry.execute(Retry.java:24)
        at com.diem.Testnet.mintCoins(Testnet.java:60)
        ... 1 more
make: *** [Makefile:14: java] Error 1

```

**Comment by jnaulty** [comment]
Seems like the current head of `master` is also broke (at ceeed96ef957d79fa8baf37adb5aa3fcdbaaf7cc)
```
Build Done! jar could be found at /test/java/build/libs                                                                                                                                                                                                                                                                       
moved to: /test/java/build/libs                                                                                                                                                                                                                                                                                               
Execute java examples:                                                                                                                                                                                                                                                                                                        
Generate keys example:                                                                                                                                                                                                                                                                                                        
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GenerateKeysExampleGenerated address: 49CA74DFE68D5AFE56AF9E6273A9126D                                                                                                                                                                                      
Auth Key (HEX): 6EEDAEDC4C32FC727F8202AFA023F55E49CA74DFE68D5AFE56AF9E6273A9126D                                                                                                                                                                                                                                              
Public key (HEX): F1B9C5550CB90A57A0A508A85A1F59942493D81DED8DF79252CAAA422D00A4EC                                                                                                                                                                                                                                            
Mint Example: 
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.MintExampleGenerated address: 6D1BA4BCC7D3718541BFBB6D791E574F
Exception in thread "main" java.lang.RuntimeException: org.libra.jsonrpc.ChainIdMismatchException: chainId mismatch! Expected: org.libra.types.ChainId@db Received: 0
        at org.libra.Testnet.mintCoins(Testnet.java:46)
        at example.MintExample.main(MintExample.java:29)
Caused by: org.libra.jsonrpc.ChainIdMismatchException: chainId mismatch! Expected: org.libra.types.ChainId@db Received: 0
        at org.libra.jsonrpc.LedgerState.validateLedgerState(LedgerState.java:48)
        at org.libra.jsonrpc.LedgerState.save(LedgerState.java:39)
        at org.libra.jsonrpc.LibraJsonRpcClient.callWithoutRetry(LibraJsonRpcClient.java:306)
        at org.libra.jsonrpc.LibraJsonRpcClient.lambda$call$1(LibraJsonRpcClient.java:289)
        at org.libra.jsonrpc.Retry.execute(Retry.java:24)
        at org.libra.jsonrpc.LibraJsonRpcClient.call(LibraJsonRpcClient.java:289)
        at org.libra.jsonrpc.LibraJsonRpcClient.getAccountTransaction(LibraJsonRpcClient.java:134)
        at org.libra.Testnet.waitForTransaction(Testnet.java:89)
        at org.libra.Testnet.mintCoins(Testnet.java:44)
        ... 1 more
Get Account Example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GetAccountInfoExampleException in thread "main" java.lang.RuntimeException: org.libra.jsonrpc.ChainIdMismatchException: chainId mismatch! Expected: org.libra.types.ChainId@db Received: 0
        at org.libra.Testnet.mintCoins(Testnet.java:46)
        at example.GetAccountInfoExample.main(GetAccountInfoExample.java:24)
Caused by: org.libra.jsonrpc.ChainIdMismatchException: chainId mismatch! Expected: org.libra.types.ChainId@db Received: 0
        at org.libra.jsonrpc.LedgerState.validateLedgerState(LedgerState.java:48)
        at org.libra.jsonrpc.LedgerState.save(LedgerState.java:39)
        at org.libra.jsonrpc.LibraJsonRpcClient.callWithoutRetry(LibraJsonRpcClient.java:306)
        at org.libra.jsonrpc.LibraJsonRpcClient.lambda$call$1(LibraJsonRpcClient.java:289)
        at org.libra.jsonrpc.Retry.execute(Retry.java:24)
        at org.libra.jsonrpc.LibraJsonRpcClient.call(LibraJsonRpcClient.java:289)
        at org.libra.jsonrpc.LibraJsonRpcClient.getAccountTransaction(LibraJsonRpcClient.java:134)
        at org.libra.Testnet.waitForTransaction(Testnet.java:89)
        at org.libra.Testnet.mintCoins(Testnet.java:44)
        ... 1 more
Intent Identifier Example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.IntentIdentifierExampleEncoded IntentIdentifier: libra://tlb1prwz087zflt7fy27ndlrleyamggqqqqqqqqqqqqqvhtjp9?am=10000000&c=Coin1
Account (HEX) from intent: 1B84F3F849FAFC922BD36FC7FC93BB42
Amount from intent: 10000000
Currency from intent: Coin1
Submit Peer To Peer Transaction Example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.SubmitPeerToPeerTransactionExampleException in thread "main" java.lang.RuntimeException: org.libra.jsonrpc.ChainIdMismatchException: chainId mismatch! Expected: org.libra.types.ChainId@db Received: 0
        at org.libra.Testnet.mintCoins(Testnet.java:46)
        at example.SubmitPeerToPeerTransactionExample.main(SubmitPeerToPeerTransactionExample.java:34)
Caused by: org.libra.jsonrpc.ChainIdMismatchException: chainId mismatch! Expected: org.libra.types.ChainId@db Received: 0
        at org.libra.jsonrpc.LedgerState.validateLedgerState(LedgerState.java:48)
        at org.libra.jsonrpc.LedgerState.save(LedgerState.java:39)
        at org.libra.jsonrpc.LibraJsonRpcClient.callWithoutRetry(LibraJsonRpcClient.java:306)
        at org.libra.jsonrpc.LibraJsonRpcClient.lambda$call$1(LibraJsonRpcClient.java:289)
        at org.libra.jsonrpc.Retry.execute(Retry.java:24)
        at org.libra.jsonrpc.LibraJsonRpcClient.call(LibraJsonRpcClient.java:289)
        at org.libra.jsonrpc.LibraJsonRpcClient.getAccountTransaction(LibraJsonRpcClient.java:134)
        at org.libra.Testnet.waitForTransaction(Testnet.java:89)
        at org.libra.Testnet.mintCoins(Testnet.java:44)
        ... 1 more
Get Events Example:
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GetEventsExampleException in thread "main" java.lang.RuntimeException: org.libra.jsonrpc.ChainIdMismatchException: chainId mismatch! Expected: org.libra.types.ChainId@db Received: 0
        at org.libra.Testnet.mintCoins(Testnet.java:46)
        at example.GetEventsExample.main(GetEventsExample.java:27)
Caused by: org.libra.jsonrpc.ChainIdMismatchException: chainId mismatch! Expected: org.libra.types.ChainId@db Received: 0
        at org.libra.jsonrpc.LedgerState.validateLedgerState(LedgerState.java:48)
        at org.libra.jsonrpc.LedgerState.save(LedgerState.java:39)
        at org.libra.jsonrpc.LibraJsonRpcClient.callWithoutRetry(LibraJsonRpcClient.java:306)
        at org.libra.jsonrpc.LibraJsonRpcClient.lambda$call$1(LibraJsonRpcClient.java:289)
        at org.libra.jsonrpc.Retry.execute(Retry.java:24)
        at org.libra.jsonrpc.LibraJsonRpcClient.call(LibraJsonRpcClient.java:289)
        at org.libra.jsonrpc.LibraJsonRpcClient.getAccountTransaction(LibraJsonRpcClient.java:134)
        at org.libra.Testnet.waitForTransaction(Testnet.java:89)
        at org.libra.Testnet.mintCoins(Testnet.java:44)
        ... 1 more
```

**Comment by jnaulty** [comment]
Latest changes (change currency from `Coin1` to `XUS`

```
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :shadowJar UP-TO-DATE

BUILD SUCCESSFUL in 563ms
2 actionable tasks: 2 up-to-date

[0;32mBuild Done![0m jar could be found at /test/java/build/libs
moved to: /test/java/build/libs
[0;31mExecute java examples:[0m
[0;35mGenerate keys example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GenerateKeysExampleGenerated address: B5A5A724768061A80937163BD7C2E697
Auth Key (HEX): D12B1F97912AD1FCC201BDAF1348B6E7B5A5A724768061A80937163BD7C2E697
Public key (HEX): 6B68DE16E4BFF4A2CED22E05F34A86E6FD87C5D9402407B0CA29DB6FBE177F3E
[0;35mMint Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.MintExampleGenerated address: 8A41C58C90755A4E725F1848A9BD59D6
[0;35mGet Account Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GetAccountInfoExampleAccount info:
address: "cda56499a08e1871fe9abb87d4b1a26d"
balances {
  amount: 1000000000
  currency: "XUS"
}
authentication_key: "7ad22657f920bb202158caf481acae94cda56499a08e1871fe9abb87d4b1a26d"
sent_events_key: "0300000000000000cda56499a08e1871fe9abb87d4b1a26d"
received_events_key: "0200000000000000cda56499a08e1871fe9abb87d4b1a26d"
role {
  type: "parent_vasp"
  human_name: "No. 57739 VASP"
  expiration_time: 18446744073709551615
  compliance_key_rotation_events_key: "0000000000000000cda56499a08e1871fe9abb87d4b1a26d"
  base_url_rotation_events_key: "0100000000000000cda56499a08e1871fe9abb87d4b1a26d"
}

[0;35mIntent Identifier Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.IntentIdentifierExampleEncoded IntentIdentifier: diem://tdm1prdf7cqwpy9kt6zkjzcm4jjnn4cqqqqqqqqqqqqqf7w7ku?am=10000000&c=XUS
Account (HEX) from intent: 1B53EC01C1216CBD0AD21637594A73AE
Amount from intent: 10000000
Currency from intent: XUS
[0;35mSubmit Peer To Peer Transaction Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.SubmitPeerToPeerTransactionExampleversion: 74300299
transaction {
  type: "user"
  sender: "684537af1eff0ef9412eb941cee32a84"
  signature_scheme: "Scheme::Ed25519"
  signature: "2c616137159a7aa67082b8515289bd21309bb4dd032a1d3e5d12ef294fe9d1208d01579e3e69438523de8c45159b1b7b8de94a424960f11f583eb70457819706"
  public_key: "1202d0bb39ac6e25c45bada7951e5eefd0c1c3a115edddc6927f13c18dbd471f"
  chain_id: 2
  max_gas_amount: 1000000
  gas_currency: "XUS"
  expiration_timestamp_secs: 1615400479
  script_hash: "04ea43107fafc12adcd09f6c68d63e194675d0ce843a7faf7cceb6c813db9d9a"
  script_bytes: "e001a11ceb0b010000000701000202020403061004160205181d0735600895011000000001010000020001000003020301010004010300010501060c0108000506080005030a020a020005060c05030a020a020109000b4469656d4163636f756e741257697468647261774361706162696c6974791b657874726163745f77697468647261775f6361706162696c697479087061795f66726f6d1b726573746f72655f77697468647261775f6361706162696c69747900000000000000000000000000000001010104010c0b0011000c050e050a010a020b030b0438000b051102020107000000000000000000000000000000010358555303585553000403eb1f21a4144dd7680fab7d802754fbfe01809698000000000004000400"
  script {
    type: "peer_to_peer_with_metadata"
    code: "a11ceb0b010000000701000202020403061004160205181d0735600895011000000001010000020001000003020301010004010300010501060c0108000506080005030a020a020005060c05030a020a020109000b4469656d4163636f756e741257697468647261774361706162696c6974791b657874726163745f77697468647261775f6361706162696c697479087061795f66726f6d1b726573746f72655f77697468647261775f6361706162696c69747900000000000000000000000000000001010104010c0b0011000c050e050a010a020b030b0438000b05110202"
    arguments: "{ADDRESS: EB1F21A4144DD7680FAB7D802754FBFE}"
    arguments: "{U64: 10000000}"
    arguments: "{U8Vector: 0x}"
    arguments: "{U8Vector: 0x}"
    type_arguments: "XUS"
    receiver: "eb1f21a4144dd7680fab7d802754fbfe"
    amount: 10000000
    currency: "XUS"
  }
}
hash: "70c6900d04ec27799508d7a5e523ccbf43f1fbe3d497778f201c3d76169d8557"
bytes: "00684537af1eff0ef9412eb941cee32a84000000000000000001e001a11ceb0b010000000701000202020403061004160205181d0735600895011000000001010000020001000003020301010004010300010501060c0108000506080005030a020a020005060c05030a020a020109000b4469656d4163636f756e741257697468647261774361706162696c6974791b657874726163745f77697468647261775f6361706162696c697479087061795f66726f6d1b726573746f72655f77697468647261775f6361706162696c69747900000000000000000000000000000001010104010c0b0011000c050e050a010a020b030b0438000b051102020107000000000000000000000000000000010358555303585553000403eb1f21a4144dd7680fab7d802754fbfe0180969800000000000400040040420f00000000000000000000000000035855531f0e4960000000000200201202d0bb39ac6e25c45bada7951e5eefd0c1c3a115edddc6927f13c18dbd471f402c616137159a7aa67082b8515289bd21309bb4dd032a1d3e5d12ef294fe9d1208d01579e3e69438523de8c45159b1b7b8de94a424960f11f583eb70457819706"
events {
  key: "0300000000000000684537af1eff0ef9412eb941cee32a84"
  transaction_version: 74300299
  data {
    type: "sentpayment"
    amount {
      amount: 10000000
      currency: "XUS"
    }
    sender: "684537af1eff0ef9412eb941cee32a84"
    receiver: "eb1f21a4144dd7680fab7d802754fbfe"
  }
}
events {
  key: "0200000000000000eb1f21a4144dd7680fab7d802754fbfe"
  sequence_number: 1
  transaction_version: 74300299
  data {
    type: "receivedpayment"
    amount {
      amount: 10000000
      currency: "XUS"
    }
    sender: "684537af1eff0ef9412eb941cee32a84"
    receiver: "eb1f21a4144dd7680fab7d802754fbfe"
  }
}
vm_status {
  type: "executed"
}
gas_used: 481

[0;35mGet Events Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GetEventsExample1 new events found
Event #1:
key: "0200000000000000ec9084754f72ea4e791d65b5991e8231"
transaction_version: 74300308
data {
  type: "receivedpayment"
  amount {
    amount: 100000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "ec9084754f72ea4e791d65b5991e8231"
}

Exception in thread "Thread-1" java.lang.RuntimeException: Mint coins failed
	at com.diem.Testnet.mintCoins(Testnet.java:68)
	at example.GetEventsExample.lambda$startMinter$1(GetEventsExample.java:78)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.diem.jsonrpc.DiemTransactionHashMismatchException: found transaction, but hash does not match, expected 665094E5851C49427E68FF7B689B9DB83041A6472A8916D8CB9308EFDE90C387, but got 0a547280e0438d0c9f519bc0aa39c80e82d2499559cfeb4f2fa573cc2da90a39
	at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:221)
	at com.diem.jsonrpc.DiemJsonRpcClient.waitForTransaction(DiemJsonRpcClient.java:198)
	at com.diem.Testnet.lambda$mintCoins$0(Testnet.java:63)
	at com.diem.jsonrpc.Retry.execute(Retry.java:24)
	at com.diem.Testnet.mintCoins(Testnet.java:60)
	... 2 more
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found

```

**Comment by jnaulty** [comment]
two exceptions:
```
root@03852041afc5:/test/java# grep -i 'exception' build.log
Exception in thread "Thread-1" java.lang.RuntimeException: Mint coins failed
Caused by: com.diem.jsonrpc.DiemTransactionHashMismatchException: found transaction, but hash does not match, expected 665094E5851C49427E68FF7B689B9DB83041A6472A8916D8CB9308EFDE90C387, but got 0a547280e0438d0c9f519bc0aa39c80e82d2499559cfeb4f2fa573cc2da90a39

```

**Comment by jnaulty** [comment]
The issue I encountered does not seem to be reproducible, the `make java` flow works now without throwing exceptions OR I messed something up on my end on my first try, and when I came back, I did things the 'right way' :thinking: 

So, I believe this PR is 'good to go' and ready for review :)

```
Found correct java version
Found correct gradle version
cd java/; ./make-java.sh
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :shadowJar UP-TO-DATE

BUILD SUCCESSFUL in 659ms
2 actionable tasks: 2 up-to-date

[0;32mBuild Done![0m jar could be found at /test/java/build/libs
moved to: /test/java/build/libs
[0;31mExecute java examples:[0m
[0;35mGenerate keys example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GenerateKeysExampleGenerated address: A1D7B03620322387566DF1D34D5DEC66
Auth Key (HEX): 65ED71A48A95D54BD2A9F6F388CE3350A1D7B03620322387566DF1D34D5DEC66
Public key (HEX): 274F323C5FC2E9536A852A4317083A85BA30AF291DE131B11C149D565AE2125C
[0;35mMint Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.MintExampleGenerated address: 3D05C3B5722FE30F1591DC460AEC1C31
[0;35mGet Account Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GetAccountInfoExampleAccount info:
address: "de26b309d71528bf4f2f2bff2e4c6899"
balances {
  amount: 1000000000
  currency: "XUS"
}
authentication_key: "a646d321c4546d2b679e53281c5f257dde26b309d71528bf4f2f2bff2e4c6899"
sent_events_key: "0300000000000000de26b309d71528bf4f2f2bff2e4c6899"
received_events_key: "0200000000000000de26b309d71528bf4f2f2bff2e4c6899"
role {
  type: "parent_vasp"
  human_name: "No. 58051 VASP"
  expiration_time: 18446744073709551615
  compliance_key_rotation_events_key: "0000000000000000de26b309d71528bf4f2f2bff2e4c6899"
  base_url_rotation_events_key: "0100000000000000de26b309d71528bf4f2f2bff2e4c6899"
}

[0;35mIntent Identifier Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.IntentIdentifierExampleEncoded IntentIdentifier: diem://tdm1p9mtjl708maa6qfd9c792ssqmgvqqqqqqqqqqqqqdeff8e?am=10000000&c=XUS
Account (HEX) from intent: 2ED72FF9E7DF7BA025A5C78AA8401B43
Amount from intent: 10000000
Currency from intent: XUS
[0;35mSubmit Peer To Peer Transaction Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.SubmitPeerToPeerTransactionExampleversion: 74405430
transaction {
  type: "user"
  sender: "260fa5018a48b0bcbdc032e2f19cc59e"
  signature_scheme: "Scheme::Ed25519"
  signature: "a0e75b6118466799a6a3977cda33fcaa66284b600e497b05617bf1820f1545b77a07f614268fb71eda1456b1672d5e045e92f89bedb4e87e046f1d5e1b77ce04"
  public_key: "bf399c0cc5b87fc0e3af6961a0a98306007505a8194e5617562ed8e8d8415364"
  chain_id: 2
  max_gas_amount: 1000000
  gas_currency: "XUS"
  expiration_timestamp_secs: 1615417745
  script_hash: "04ea43107fafc12adcd09f6c68d63e194675d0ce843a7faf7cceb6c813db9d9a"
  script_bytes: "e001a11ceb0b010000000701000202020403061004160205181d0735600895011000000001010000020001000003020301010004010300010501060c0108000506080005030a020a020005060c05030a020a020109000b4469656d4163636f756e741257697468647261774361706162696c6974791b657874726163745f77697468647261775f6361706162696c697479087061795f66726f6d1b726573746f72655f77697468647261775f6361706162696c69747900000000000000000000000000000001010104010c0b0011000c050e050a010a020b030b0438000b051102020107000000000000000000000000000000010358555303585553000403bb6bb39c4b763276701b08b4fabacda801809698000000000004000400"
  script {
    type: "peer_to_peer_with_metadata"
    code: "a11ceb0b010000000701000202020403061004160205181d0735600895011000000001010000020001000003020301010004010300010501060c0108000506080005030a020a020005060c05030a020a020109000b4469656d4163636f756e741257697468647261774361706162696c6974791b657874726163745f77697468647261775f6361706162696c697479087061795f66726f6d1b726573746f72655f77697468647261775f6361706162696c69747900000000000000000000000000000001010104010c0b0011000c050e050a010a020b030b0438000b05110202"
    arguments: "{ADDRESS: BB6BB39C4B763276701B08B4FABACDA8}"
    arguments: "{U64: 10000000}"
    arguments: "{U8Vector: 0x}"
    arguments: "{U8Vector: 0x}"
    type_arguments: "XUS"
    receiver: "bb6bb39c4b763276701b08b4fabacda8"
    amount: 10000000
    currency: "XUS"
  }
}
hash: "afdb0a2952f87eccae729b88b280e1a5b23e48bffcef43afa8a2ac9996c57a8c"
bytes: "00260fa5018a48b0bcbdc032e2f19cc59e000000000000000001e001a11ceb0b010000000701000202020403061004160205181d0735600895011000000001010000020001000003020301010004010300010501060c0108000506080005030a020a020005060c05030a020a020109000b4469656d4163636f756e741257697468647261774361706162696c6974791b657874726163745f77697468647261775f6361706162696c697479087061795f66726f6d1b726573746f72655f77697468647261775f6361706162696c69747900000000000000000000000000000001010104010c0b0011000c050e050a010a020b030b0438000b051102020107000000000000000000000000000000010358555303585553000403bb6bb39c4b763276701b08b4fabacda80180969800000000000400040040420f00000000000000000000000000035855539151496000000000020020bf399c0cc5b87fc0e3af6961a0a98306007505a8194e5617562ed8e8d841536440a0e75b6118466799a6a3977cda33fcaa66284b600e497b05617bf1820f1545b77a07f614268fb71eda1456b1672d5e045e92f89bedb4e87e046f1d5e1b77ce04"
events {
  key: "0300000000000000260fa5018a48b0bcbdc032e2f19cc59e"
  transaction_version: 74405430
  data {
    type: "sentpayment"
    amount {
      amount: 10000000
      currency: "XUS"
    }
    sender: "260fa5018a48b0bcbdc032e2f19cc59e"
    receiver: "bb6bb39c4b763276701b08b4fabacda8"
  }
}
events {
  key: "0200000000000000bb6bb39c4b763276701b08b4fabacda8"
  sequence_number: 1
  transaction_version: 74405430
  data {
    type: "receivedpayment"
    amount {
      amount: 10000000
      currency: "XUS"
    }
    sender: "260fa5018a48b0bcbdc032e2f19cc59e"
    receiver: "bb6bb39c4b763276701b08b4fabacda8"
  }
}
vm_status {
  type: "executed"
}
gas_used: 481

[0;35mGet Events Example:[0m
execute: java -cp java-code-examples-1.0-SNAPSHOT-all.jar example.GetEventsExample1 new events found
Event #1:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
transaction_version: 74405439
data {
  type: "receivedpayment"
  amount {
    amount: 100000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

1 new events found
Event #1:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 1
transaction_version: 74405447
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

1 new events found
Event #1:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 2
transaction_version: 74405457
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

2 new events found
Event #1:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 3
transaction_version: 74405469
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

Event #2:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 4
transaction_version: 74405479
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

1 new events found
Event #1:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 5
transaction_version: 74405489
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

1 new events found
Event #1:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 6
transaction_version: 74405498
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

2 new events found
Event #1:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 7
transaction_version: 74405509
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

Event #2:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 8
transaction_version: 74405519
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

1 new events found
Event #1:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 9
transaction_version: 74405529
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

1 new events found
Event #1:
key: "02000000000000004f493c9ce8222aae2c86d58f8623fe0b"
sequence_number: 10
transaction_version: 74405539
data {
  type: "receivedpayment"
  amount {
    amount: 1000000
    currency: "XUS"
  }
  sender: "000000000000000000000000000000dd"
  receiver: "4f493c9ce8222aae2c86d58f8623fe0b"
}

0 new events found
0 new events found
0 new events found
0 new events found
0 new events found
0 new events found

```

**Comment by yanivmo** [comment]
Thanks for the help!
Actually you and I made exactly the same fixes simultaneously hehe.
Merging!

**Pull request merged**
